name: portfolio

on:
  workflow_dispatch:
  
permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      
      - name: setup the pages
        uses: actions/configure-pages@v4

      - name: static code artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "."
        

      - name: deploy or go live

        uses: actions/deploy-pages@v4



